version: 2.1
dependencies:
  pre:
    - run:
      name: Avoid hosts unknown for github
      command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - git clone -b circleci-project-setup git@github.com:consumere/tsjl.git ~/tsjl
working_directory: ~/tsjl

orbs:
  docker: circleci/docker@1.7.0
  
jobs:
  - docker/publish:
      docker-password: $dpw 
      docker-username: $DN 
      image: julia:latest 
      tag: consumere/shinyapp:tsjl-ci
  - run: ls -l
  - run: echo "tsjl-ci workflow done!"