version: 2.1
working_directory: ~/tsjl
jobs: 
 build:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - checkout
   # build the image
      - run: |
         ls -halt 
         #cp -v DF Dockerfile       #
         docker build . -t consumere/shinyapps:tsjl-ci
     # deploy the image
      - run: docker push consumere/shinyapps:tsjl-ci
      - run: echo "push  consumere/shinyapps:tsjl-ci done!"
      - run: ls -l
      - run: echo "tsjl-ci workflow done!"

  